language: node_js
node_js:
    - '12'


before_install:
    npm install
install: true

before_script: true
script:
    #- ./node_modules/.bin/Jshint
    #- ./node_modules/.bin/Retire
    #- ./node_modules/.bin/Twly

after_script: true
