language: node_js
php:
- '12'
cache:
 directories:
   - $HOME/.composer/cache

before_install: true
install: true

before_script: true
script:true

after_script: true

deploy:
 provider: heroku
 api_key:
   secure: "cle"
 app: app-evaluation
